### ISSUE TITLE
Custom Plot Resampling 

### ISSUE THREAD

**Issue by mabi38** [jkall/qgis-midvatten-plugin#351] opened 2024-01-08 20:43 UTC
I tried to resample a data set using the resample option provided in the custom plot generator. The dateset includes daily data for a period of 3 months, each day one value. By the resampling I would like to convert the daily data to weekly data. 
Following the short description which pops up entering the fields in the resampling section I added:
- W for 'resampling rule'
- 0 for 'resample base' (Honestly I need to say that I did not understand what is meant with "the hour to start....". The cited pandas documentation didn't help, either. So I selected 0 defined as default value.)
- mean for 'resampling how'.
The other fields I left blank.
Clicking on 'Plot chart' I received the following error message: TypeError: resample() got an unexpected keyword argument 'base'.
Other integer values for the resample base field reveal the same error message. 

It would be great getting some help to understand what went wrong.

Thank you very much.

Martin

**Comment by HenrikSpa** [comment] 2024-01-09 08:11
You are using it correctly. The error is caused by a change in the Python pandas library in one of the later QGIS LTR-versions. I have made a fix for this and will upload a new Midvatten version very soon. 

Resample base: 
If you resample to rule '24h', base is the hour to start the resampling.

Base=0 gives a daily aggregate like 2024-01-09 00:00 to 2024-01-10 00:00
Base=6 gives instead a daily aggregate like 2024-01-09 06:00 to 2024-01-10 06:00

If you resample to 60T, base=30 will (probably, I have not tested) give you 2024-01-09 00:30 to 2024-01-09 01:30.

Regards,
Henrik

**Comment by HenrikSpa** [comment] 2024-01-09 08:17
There is now a Midvatten plugin version 1.7.18 available which requires QGIS >= 3.28.13.

**Closed by HenrikSpa** 2024-01-09 08:17 UTC
