### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#226] opened 2017-03-25 19:10 UTC
The plugin should be updated to make translations easier.
(https://jamesinnorway.wordpress.com/2014/04/08/translation-of-qgis-plugins/)

Howto:

1) Update all files:
Add
tr = PyQt4.QtCore.QCoreApplication.translate
after the imports in each file.

Surround each string with the function tr():
ex 1:
class A:
    print("a string")
    print("string %s"%"2")
-->
class A:
    print(tr("A", "a string"))
    print(tr("A", "string %s"%"2"))

The first argument is a "context" string that could be anything, but using the class where it's at is probably a good idea.

2) Update translation files:
Go to folder i18n in midvatten plugin folder (currently in branch postgis_henrik)
Update file translations.pro by adding the py-files that have the tr() functions in them.

Then run:
pylupdate4 -noobsolete translations.pro
to update default_eng.ts.

**Comment by jkall** [comment] 2017-03-26 16:36
closing this since it is a duplicate of already reported issue https://github.com/jkall/qgis-midvatten-plugin/issues/82

**Closed by jkall** 2017-03-26 16:36 UTC
